pipeline:
  docker:
    image: earthly/earthly:v0.6.28
    group: build
    commands:
      - earthly --ci --push +image
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

depends_on:
  - lint
  - test
