pipeline:
  build:
    image: earthly/earthly:v0.6.28
    group: build
    commands:
      - earthly --ci +build-all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

depends_on:
  - lint
  - test
