pipeline:
  test:
    image: earthly/earthly:v0.6.28
    group: test
    commands:
      - earthly --ci +test
      - earthly --ci +codecov --CODECOV_TOKEN=${CODECOV_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

depends_on:
  - lint
